daily_prompts = [
    "What was the most memorable part of today?"
    "What made you smile today?",
    "What are you grateful for right now?",
    "Describe a recent accomplishment.",
    "What's something you're looking forward to?",
    "Write about a challenge you overcame.",
    "List three things that inspire you.",
    "What's something you're proud of?",
    "Reflect on a recent conversation that impacted you.",
    "Write about a goal you're working towards.",
    "Describe your ideal day.",
    "What's something that brings you peace?",
    "Write about a place you love.",
    "What's a hobby you enjoy?",
    "Reflect on a mistake and what you learned from it.",
    "List things that make you feel energized.",
    "Describe your favorite memory.",
    "Write a letter to your future self.",
    "What's a book or movie that impacted you?",
    "List things that make you feel calm.",
    "Reflect on a time you felt proud of yourself.",
    "Describe your favorite season and why.",
    "What's something you want to learn?",
    "Write about a challenge you're facing.",
    "List your strengths.",
    "Reflect on a person who inspires you.",
    "Describe a time you felt grateful for something small.",
    "What's a dream you have for the near future?",
    "What made you smile today?",
    "What are you grateful for right now?",
    "Describe a recent accomplishment.",
    "What's something you're looking forward to?",
    "Write about a challenge you overcame.",
    "List three things that inspire you.",
    "What's something you're proud of?",
    "Reflect on a recent conversation that impacted you.",
    "Write about a goal you're working towards.",
    "Describe your ideal day.",
    "What's something that brings you peace?",
    "Write about a place you love.",
    "What's a hobby you enjoy?",
    "Reflect on a mistake and what you learned from it.",
    "List things that make you feel energized.",
    "Describe your favorite memory.",
    "Write a letter to your future self.",
    "What's a book or movie that impacted you?",
    "List things that make you feel calm.",
    "Reflect on a time you felt proud of yourself.",
    "Describe your favorite season and why.",
    "What's something you want to learn?",
    "Write about a challenge you're facing.",
    "List your strengths.",
    "Reflect on a person who inspires you.",
    "Describe a time you felt grateful for something small.",
    "What's a dream you have for the future?",
    "How did you feel when you woke up today?",
    "Describe a moment today when you felt happy.",
    "What's something that made you laugh today?",
    "Reflect on a time today when you felt grateful.",
    "Describe a challenge you faced today and how you handled it emotionally.",
    "What's something that made you feel proud today?",
    "Write about a moment of sadness or disappointment you experienced today.",
    "Describe a situation today that made you feel anxious or stressed.",
    "Reflect on a moment today when you felt inspired.",
    "What's something that brought you peace or calmness today?",
    "Write about a moment today when you felt excited or enthusiastic.",
    "Describe a conversation today that had a significant emotional impact on you.",
    "Reflect on a moment today when you felt proud of someone else.",
    "What's an emotion you experienced today that you didn't expect?",
    "Write about a moment today when you felt connected to someone.",
    "Describe a moment today when you felt motivated.",
    "What's a lesson you learned about yourself today?",
    "Reflect on a moment today when you felt overwhelmed and how you managed it.",
    "Write about a moment today when you felt grateful for your health.",
    "Describe a moment today when you felt proud of your accomplishments.",
    "What's something you're looking forward to tomorrow?",
    "Reflect on a moment today when you felt a sense of achievement.",
    "Write about a moment today when you felt confident in yourself.",
    "Describe a moment today when you felt inspired by nature.",
    "What's something today that made you feel optimistic about the future?",
    "Reflect on a moment today when you felt loved or appreciated.",
    "Write about a moment today when you felt at peace with yourself.",
    "Describe a moment today when you felt a sense of belonging.",
    "What's something you're excited to do later today?",
    "Reflect on a moment today when you felt in control of your emotions.",
    "Write about a moment today when you felt proud of your resilience.",
    "Describe a moment today when you felt a sense of accomplishment.",
    "What's something you're grateful for about today?",
    "Reflect on a moment today when you felt inspired by someone's kindness.",
    "Write about a moment today when you felt a deep connection with someone.",
    "Describe a moment today when you felt motivated to pursue your goals.",
    "What's an emotion you experienced today that you want to explore further?",
    "Reflect on a moment today when you felt proud of your growth.",
    "Write about a moment today when you felt supported by someone.",
    "Describe a moment today when you felt at peace with the present moment.",
    "What's something you're excited to accomplish by the end of the week?",
    "Reflect on a moment today when you felt grateful for your experiences.",
    "Write about a moment today when you felt inspired to help others.",
    "Describe a moment today when you felt content with where you are in life.",
    "What's an emotion you experienced today that surprised you?",
    "Reflect on a moment today when you felt connected to your passions.",
    "Write about a moment today when you felt proud of your resilience.",
    "Describe a moment today when you felt a sense of wonder or awe.",
    "What's something you're looking forward to experiencing in the near future?",
    "Reflect on a moment today when you felt a deep sense of joy.",
    "Write about a moment today when you felt grateful for your relationships.",
    "Describe a moment today when you felt inspired to pursue new opportunities.",
    "What's an emotion you experienced today that you want to explore further?",
    "Reflect on a moment today when you felt proud of your progress.",
    "Write about a moment today when you felt supported by someone's encouragement.",
    "Describe a moment today when you felt at peace with the challenges you're facing.",
    "What's something you're excited to accomplish by the end of the month?",
    "Reflect on a moment today when you felt grateful for your growth.",
    "Write about a moment today when you felt inspired to make positive changes.",
    "Describe a moment today when you felt content with the person you're becoming.",
    "What's an emotion you experienced today that taught you something new?",
    "Reflect on a moment today when you felt connected to your purpose.",
    "Write about a moment today when you felt proud of your determination.",
    "Describe a moment today when you felt a sense of belonging.",
    "What's something you're looking forward to experiencing in the coming weeks?",
    "Reflect on a moment today when you felt a deep sense of gratitude.",
    "Write about a moment today when you felt inspired to pursue your dreams.",
    "Describe a moment today when you felt a sense of fulfillment.",
    "What's an emotion you experienced today that you want to explore further?",
    "Reflect on a moment today when you felt proud of your resilience.",
    "Write about a moment today when you felt supported by someone's kindness.",
    "Describe a moment today when you felt at peace with the present moment.",
    "What's something you're excited to accomplish by the end of the year?",
    "Reflect on a moment today when you felt grateful for your experiences.",
    "Write about a moment today when you felt inspired to help others.",
    "Describe a moment today when you felt content with where you are in life.",
    "What's an emotion you experienced today that surprised you?",
    "Reflect on a moment today when you felt connected to your passions.",
    "Write about a moment today when you felt proud of your resilience.",
    "Describe a moment today when you felt a sense of wonder or awe.",
    "What's something you're looking forward to experiencing in the future?",
    "Reflect on a moment today when you felt a deep sense of joy.",
    "Write about a moment today when you felt grateful for your relationships.",
    "Describe a moment today when you felt inspired to pursue new opportunities.",
    "What's an emotion you experienced today that you want to explore further?",
    "Reflect on a moment today when you felt proud of your progress.",
    "Write about a moment today when you felt supported by someone's encouragement.",
    "Describe a moment today when you felt at peace with the challenges you're facing.",
    "What's something you're excited to accomplish by the end of the month?",
    "Reflect on a moment today when you felt grateful for your growth.",
    "Write about a moment today when you felt inspired to make positive changes.",
    "Describe a moment today when you felt content with the person you're becoming.",
    "What's an emotion you experienced today that taught you something new?",
    "Reflect on a moment today when you felt connected to your purpose.",
    "Write about a moment today when you felt proud of your determination.",
    "Describe a moment today when you felt a sense of belonging.",
    "What's something you're looking forward to experiencing in the coming weeks?",
    "Reflect on a moment today when you felt a deep sense of gratitude.",
    "Write about a moment today when you felt inspired to pursue your dreams.",
    "Describe a moment today when you felt a sense of fulfillment.",
    "What's an emotion you experienced today that you want to explore further?",
    "Reflect on a moment today when you felt proud of your resilience.",
    "Write about a moment today when you felt supported by someone's kindness.",
    "Describe a moment today when you felt at peace with the present moment.",
    "What's something you're excited to accomplish by the end of the year?",
    "Reflect on a moment today when you felt grateful for your experiences.",
    "Write about a moment today when you felt inspired to help others.",
    "Describe a moment today when you felt content with where you are in life.",
    "What's an emotion you experienced today that surprised you?",
    "Reflect on a moment today when you felt connected to your passions.",
    "Write about a moment today when you felt proud of your resilience.",
    "Describe a moment today when you felt a sense of wonder or awe.",
    "What's something you're looking forward to experiencing in the future?",
    "Reflect on a moment today when you felt a deep sense of joy.",
    "Write about a moment today when you felt grateful for your relationships.",
    "Describe a moment today when you felt inspired to pursue new opportunities.",
    "What's an emotion you experienced today that you want to explore further?",
    "Reflect on a moment today when you felt proud of your progress."
]
