daily_prompts = [
    "What was the most memorable part of today?"
    "What made you smile today?",
    "Describe a recent accomplishment.",
    "What's something you're looking forward to?",
    "Write about a challenge you overcame.",
    "List three things that inspire you.",
    "What's something you're proud of?",
    "Reflect on a recent conversation that impacted you.",
    "Write about a goal you're working towards.",
    "Describe your ideal day.",
    "What's something that brings you peace?",
    "Write about a place you love.",
    "What's a hobby you enjoy?",
    "Reflect on a mistake and what you learned from it.",
    "List things that make you feel energized.",
    "Describe your favorite memory.",
    "Write a letter to your future self.",
    "What's a book or movie that impacted you?",
    "List things that make you feel calm.",
    "Reflect on a time you felt proud of yourself.",
    "Describe your favorite season and why.",
    "What's something you want to learn?",
    "Write about a challenge you're facing.",
    "List your strengths.",
    "Reflect on a person who inspires you.",
    "What's a dream you have for the future?",
    "How did you feel when you woke up today?",
    "Describe a moment today when you felt happy.",
    "What's something that made you laugh today?",
    "Describe a challenge you faced today and how you handled it emotionally.",
    "What's something that made you feel proud today?",
    "Write about a moment of sadness or disappointment you experienced today.",
    "Describe a situation today that made you feel anxious or stressed.",
    "Reflect on a moment today when you felt inspired.",
    "What's something that brought you peace or calmness today?",
    "Write about a moment today when you felt excited or enthusiastic.",
    "Describe a conversation today that had a significant emotional impact on you.",
    "Reflect on a moment today when you felt proud of someone else.",
    "What's an emotion you experienced today that you didn't expect?",
    "Write about a moment today when you felt connected to someone.",
    "Describe a moment today when you felt motivated.",
    "What's a lesson you learned about yourself today?",
    "Reflect on a moment today when you felt overwhelmed and how you managed it.",
    "Write about a moment when you felt grateful for your health.",
    "Describe a moment today when you felt proud of your accomplishments.",
    "What's something you're looking forward to tomorrow?",
    "Reflect on a moment today when you felt a sense of achievement.",
    "Write about a moment today when you felt confident in yourself.",
    "Describe a moment today when you felt inspired by nature.",
    "What's something today that made you feel optimistic about the future?",
    "Reflect on a moment today when you felt loved or appreciated.",
    "Write about a moment today when you felt at peace with yourself.",
    "Describe a moment today when you felt a sense of belonging.",
    "What's something you're excited to do later today?",
    "Reflect on a moment today when you felt in control of your emotions.",
    "Write about a moment today when you felt proud of your resilience.",
    "Describe a moment today when you felt a sense of accomplishment.",
    "What's something you're grateful for today?",
    "Reflect on a moment today when you felt inspired by someone's kindness.",
    "Write about a moment today when you felt a deep connection with someone.",
    "Describe a moment today when you felt motivated to pursue your goals.",
    "What's an emotion you experienced today that you want to explore further?",
    "Reflect on a moment today when you felt proud of your growth.",
    "Write about a moment today when you felt supported by someone.",
    "Describe a moment today when you felt at peace with the present moment.",
    "What's something you're excited to accomplish by the end of the week?",
    "Write about a moment today when you felt inspired to help others.",
    "Describe a moment today when you felt content with where you are in life.",
    "What's an emotion you experienced today that surprised you?",
    "Reflect on a moment today when you felt connected to your passions.",
    "Write about a moment today when you felt proud of your resilience.",
    "Describe a moment today when you felt a sense of wonder or awe.",
    "What's something you're looking forward to experiencing in the near future?",
    "Reflect on a moment today when you felt a deep sense of joy.",
    "Write about a moment today when you felt grateful for your relationships.",
    "Describe a moment today when you felt inspired to pursue new opportunities.",
    "Reflect on a moment today when you felt proud of your progress.",
    "Describe a goal you've set for yourself in the next year.",
    "How do you envision your life five years from now?",
    "Write about a skill you want to develop for your future career.",
    "Describe a place you hope to visit in the future and why it's significant to you.",
    "What steps are you taking to achieve your long-term goals?",
    "Reflect on a role model or mentor who inspires you to reach for your aspirations.",
    "Write about a personal project you plan to complete in the coming months.",
    "How do you see yourself contributing to your community in the future?",
    "Describe the kind of lifestyle you hope to lead in the years ahead.",
    "Write about a challenge you anticipate facing as you work towards your goals.",
    "What motivates you to keep moving forward when faced with obstacles?",
    "Describe a successful outcome you envision for yourself in the future.",
    "Reflect on the impact you hope to make in the world during your lifetime.",
    "Write about a habit you want to cultivate to support your long-term aspirations."
]
