quotes = [
    f"'The only way to do great work is to love what you do.' - Steve Jobs",
    f"'Believe you can and you're halfway there.' - Theodore Roosevelt",
    f"'The future belongs to those who believe in the beauty of their dreams.' - Eleanor Roosevelt",
    f"'You are never too old to set another goal or to dream a new dream.' - C.S. Lewis",
    f"'Success is not final, failure is not fatal: It is the courage to continue that counts.' - Winston Churchill",
    f"'In the middle of difficulty lies opportunity.' - Albert Einstein",
    f"'Keep your face always toward the sunshine—and shadows will fall behind you.' - Walt Whitman",
    f"'You are braver than you believe, stronger than you seem, and smarter than you think.' - A.A. Milne",
    f"'The best way to predict the future is to create it.' - Peter Drucker",
    f"'The only limit to our realization of tomorrow will be our doubts of today.' - Franklin D. Roosevelt",
    f"'Challenges are what make life interesting and overcoming them is what makes life meaningful.' - Joshua J. Marine",
    f"'Don't watch the clock; do what it does. Keep going.' - Sam Levenson",
    f"'It does not matter how slowly you go as long as you do not stop.' - Confucius",
    f"'Your time is limited, don't waste it living someone else's life.' - Steve Jobs",
    f"'The greatest glory in living lies not in never falling, but in rising every time we fall.' - Nelson Mandela",
    f"'The only way to achieve the impossible is to believe it is possible.' - Charles Kingsleigh (Alice in Wonderland)",
    f"'Life is 10% what happens to us and 90% how we react to it.' - Charles R. Swindoll",
    f"'The journey of a thousand miles begins with one step.' - Lao Tzu",
    f"'Nothing is impossible, the word itself says 'I'm possible'!' - Audrey Hepburn",
    f"'Dream big and dare to fail.' - Norman Vaughan",
    f"'The greatest glory in living lies not in never falling, but in rising every time we fall.' - Ralph Waldo Emerson",
    f"'The secret of getting ahead is getting started.' - Mark Twain",
    f"'I can't change the direction of the wind, but I can adjust my sails to always reach my destination.' - Jimmy Dean",
    f"'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.' - Albert Schweitzer",
    f"'Happiness is not something you postpone for the future; it is something you design for the present.' - Jim Rohn",
    f"'The only way to achieve the impossible is to believe it is possible.' - Charles Kingsleigh (Alice in Wonderland)",
    f"'The future belongs to those who believe in the beauty of their dreams.' - Eleanor Roosevelt",
    f"'No matter what you're going through, there's a light at the end of the tunnel.' - Demi Lovato",
    f"'The only limit to our realization of tomorrow will be our doubts of today.' - Franklin D. Roosevelt",
    f"'Do not wait to strike till the iron is hot, but make it hot by striking.' - William Butler Yeats",
    f"'The only way to do great work is to love what you do.' - Steve Jobs",
    f"'Your time is limited, don't waste it living someone else's life.' - Steve Jobs",
    f"'In the middle of difficulty lies opportunity.' - Albert Einstein",
    f"'Believe you can and you're halfway there.' - Theodore Roosevelt",
    f"'Keep your face always toward the sunshine—and shadows will fall behind you.' - Walt Whitman",
    f"'It does not matter how slowly you go as long as you do not stop.' - Confucius",
    f"'Don't watch the clock; do what it does. Keep going.' - Sam Levenson",
    f"'Challenges are what make life interesting and overcoming them is what makes life meaningful.' - Joshua J. Marine",
    f"'You are never too old to set another goal or to dream a new dream.' - C.S. Lewis",
    f"'Success is not final, failure is not fatal: It is the courage to continue that counts.' - Winston Churchill",
    f"'You are braver than you believe, stronger than you seem, and smarter than you think.' - A.A. Milne",
    f"'The best way to predict the future is to create it.' - Peter Drucker",
    f"'The journey of a thousand miles begins with one step.' - Lao Tzu",
    f"'Nothing is impossible, the word itself says 'I'm possible'!' - Audrey Hepburn",
    f"'Dream big and dare to fail.' - Norman Vaughan",
    f"'The only way to achieve the impossible is to believe it is possible.' - Charles Kingsleigh (Alice in Wonderland)",
    f"'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.' - Albert Schweitzer",
    f"'Happiness is not something you postpone for the future; it is something you design for the present.' - Jim Rohn",
    f"'The secret of getting ahead is getting started.' - Mark Twain",
    f"'I can't change the direction of the wind, but I can adjust my sails to always reach my destination.' - Jimmy Dean",
]